const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "manifest.json"), "utf8"));
const entry = fs.readFileSync(path.join(root, "src/entrystory.js"), "utf8");
const common = fs.readFileSync(path.join(root, "src/common.js"), "utf8");
const loader = fs.readFileSync(path.join(root, "src/entrystory-loader.js"), "utf8");
const nativeLive = fs.readFileSync(path.join(root, "src/entrystory-native-live.js"), "utf8");
const popup = fs.readFileSync(path.join(root, "popup/popup.html"), "utf8");
const popupJs = fs.readFileSync(path.join(root, "popup/popup.js"), "utf8");
const darkMode = fs.readFileSync(path.join(root, "src/dark-mode.js"), "utf8");
const darkModeCss = fs.readFileSync(path.join(root, "styles/dark-mode.css"), "utf8");
const darkModePagesCss = fs.readFileSync(path.join(root, "styles/dark-mode-pages.css"), "utf8");
const entryStoryCss = fs.readFileSync(path.join(root, "styles/entrystory.css"), "utf8");
const profileCss = fs.readFileSync(path.join(root, "styles/profile.css"), "utf8");
const profile = fs.readFileSync(path.join(root, "src/profile.js"), "utf8");

for (const forbidden of [
  "break7.net",
  "content.php?type=poll",
  "content.php?type=secret",
  "createPollCard",
  "createSecretCard",
  "createMathNode",
  "Lite.graph",
  "isOriginalDisconnectActive",
  "entry-chat-compose-more-toggle",
  "window.DnxLite",
  "data-entry-chat-lite-",
  "dnx_lite_",
  "X-LLNKKR-Device-Token",
  "X-LLNKKR-Client",
  "X-LLNKKR-Entry-Id",
  "X-LLNKKR-Nickname",
  "invite",
  "presence.php",
  "register.php",
]) {
  assert.equal(entry.includes(forbidden) || common.includes(forbidden) || loader.includes(forbidden) || popup.includes(forbidden), false, `${forbidden} 잔여 코드가 없어야 합니다.`);
}

assert.equal(/\\?\{(?:e|enter)\}/i.test(entry), false, "예전 줄바꿈 문법을 해석하면 안 됩니다.");
assert.match(entry, /const disabledLabelLink =/);
assert.match(entry, /appendPlainText\(nodes, disabledLabelLink\[0\]\)/);
assert.match(entry, /const DRAFT_TTL_MS = 24 \* 60 \* 60 \* 1000/);
assert.match(entry, /const LINE_BREAK_MARKER = " "\.repeat\(3\)/);
assert.match(entry, /const MAX_LINE_BREAKS = 10/);
assert.match(entry, /const isNewline = !inCode/);
assert.match(entry, /\{ key: "naverShortLinks", label: "네이버 단축 링크", depth: 2, parent: "externalLinks" \}/);
assert.match(entry, /url\.hostname === "naver\.me" \|\| url\.hostname\.endsWith\("\.naver\.me"\)/);
assert.match(entry, /state\.storyFilters\.naverShortLinks && content\.hasNaverShortLink/);
assert.match(entry, /const breakCount = Math\.floor\(runLength \/ LINE_BREAK_MARKER\.length\)/);
assert.equal(entry.includes("\\*[^*\\n]+\\*"), true);
assert.match(entry, /renderNativePostFromData\(nativeRow, post\)/);
assert.match(entry, /function primeNativeLivePostArrival\(detail = \{\}\)/);
assert.match(entry, /function animatePendingNativeRows\(node\)/);
assert.match(entry, /function isStoryPostFiltered\(post\)/);
assert.match(entry, /animateExistingRowsForInsertion\(uniqueRows\.filter\(\(row\) => !isStoryPostFiltered\(row\)\)\)/);
assert.match(entry, /pendingRoots\.forEach[\s\S]*pendingArrivalRoots\.forEach\(animatePendingNativeRows\)/);
assert.match(entry, /if \(isStoryPostFiltered\(row\)\) \{[\s\S]*row\.dataset\.entryLlnkArrivalDelivered = "1";[\s\S]*return;/);
assert.match(entry, /if \(isStoryPostFiltered\(row\)\) \{\s*if \(state\.nativeArrivalPending\) \{\s*state\.nativeArrivalPending -= 1;/);
assert.doesNotMatch(entry, /if \(isStoryPostFiltered\(row\)\) \{\s*if \(state\.nativeArrivalPending\) \{\s*state\.nativeArrivalSequence \+= 1;/);
assert.match(entry, /function isPendingSubmittedRow\(row, submittedValue = state\.draftSubmittedValue\)/);
assert.match(entry, /resetWriterAfterConfirmedPost\(submittedValue\);/);
assert.match(entry, /const isKnownFailureContainer = isChallengeContainer/);
assert.match(entry, /if \(!isKnownFailureContainer\) return false/);
assert.match(entry, /if \(suppressPendingDraftInWriter\(writer\)\) return/);
assert.doesNotMatch(entry, /checks < 24/);
assert.match(entry, /const shouldResetWriter = !currentValue\.trim\(\) \|\| !expected \|\| current === expected/);
assert.match(entry, /row\.dataset\.entryLlnkArrivalDelivered = "1"/);
assert.doesNotMatch(entry, /state\.draftSubmitPendingUntil && hasDialog\(node\)/);
assert.match(entry, /function animateExistingRowsForInsertion\(rows = \[\], list = getList\(\)\)/);
assert.match(entry, /function captureNativeArrivalScrollAnchor\(list = getList\(\)\)/);
assert.match(entry, /function restoreNativeArrivalScrollAnchor\(consume = false\)/);
assert.match(entry, /const viewportStabilized = restoreNativeArrivalScrollAnchor\(true\)/);
assert.match(entry, /if \(arrivalPostAdded\) restoreNativeArrivalScrollAnchor\(\)/);
assert.match(entry, /behavior: "instant"/);
assert.match(entry, /if \(!viewportStabilized && !window\.matchMedia/);
assert.match(entry, /if \(count\) \{\s*snapshotLiveRowPositions\(\);\s*captureNativeArrivalScrollAnchor\(\);/);
assert.match(entry, /duration: 240, easing: "cubic-bezier\(0\.22, 1, 0\.36, 1\)"/);
assert.match(nativeLive, /const REMOVED_POST_TTL = 120000/);
assert.match(nativeLive, /function observeRemovedPostIds\(queryKey\)/);
assert.match(nativeLive, /function withoutSuppressedPosts\(dl\)/);
assert.doesNotMatch(nativeLive, /now - createdAt < 30000/);
assert.match(nativeLive, /entry-llnk-native-posts-will-remove/);
assert.match(nativeLive, /postsJson: JSON\.stringify\(removedPosts\)/);
assert.match(nativeLive, /function getContentUpdatedPosts\(queryKey, dl\)/);
assert.match(nativeLive, /entry-llnk-native-posts-will-update/);
assert.match(nativeLive, /entry-llnk-native-posts-updated/);
assert.match(nativeLive, /postsJson: JSON\.stringify\(incomingPosts\)/);
assert.match(entry, /function playLivePostRemovalPickup/);
assert.match(entry, /function playLivePostUpdateRestore/);
assert.match(entry, /function primeNativeLivePostUpdate/);
assert.match(entry, /function completeNativeLivePostUpdate/);
assert.match(entry, /function freezeLivePostUpdateLayout/);
assert.match(entry, /function resizeLivePostUpdateLayout/);
assert.match(entry, /height 680ms cubic-bezier/);
assert.match(entryStoryCss, /@keyframes entry-llnk-live-post-restored/);
assert.match(entryStoryCss, /@keyframes entry-llnk-live-post-interference/);
assert.match(entryStoryCss, /calc\(50% - 10px\)/);
assert.match(entry, /beamOpacity = 0\.94 \* clamp\(local \/ 0\.1, 0, 1\) \* clamp\(\(1 - local\) \/ 0\.12, 0, 1\)/);
assert.match(nativeLive, /setTimeout\(resolve, 860\)/);
assert.match(entry, /function animateExistingRowsAfterRemoval/);
assert.match(entry, /function playLivePostArrivalDelivery\(row, delay = 0, showShip = true\)/);
assert.match(entry, /function primeNativeLivePostArrival\(detail = \{\}\) \{[\s\S]*?maybeClearSubmittedDraft\(incomingPosts\)/);
assert.match(entry, /const showShip = state\.nativeArrivalSequence === 0/);
assert.match(entry, /const isSubmittedRow = isPendingSubmittedRow\(row, submittedValue\)/);
assert.match(entry, /if \(isSubmittedRow\) \{[\s\S]*?const showShip = true/);
assert.match(entry, /row\.dataset\.entryLlnkArrivalDelivered = "1"/);
assert.match(nativeLive, /postSyncRunning/);
assert.match(nativeLive, /!suppressedPostIds\.has\(post\.id\)/);
assert.match(entry, /let removalObserved = false/);
assert.match(entry, /if \(shouldAnimateRemoval\) animateExistingRowsAfterRemoval\(\)/);
assert.match(entryStoryCss, /\.entry-llnk-moving-after-removal\.is-moving-after-removal/);
assert.match(popup, /data-setting="spaceshipMotion"/);
assert.match(popupJs, /spaceshipMotion: true/);
assert.match(popup, /data-setting="shortenProjectLinks"/);
assert.match(popupJs, /shortenProjectLinks: true/);
assert.match(entry, /function clearSpaceshipMotionEffects\(\)/);
assert.match(entry, /const motionWritingProgress = Math\.max\(initialProgress, typingProgress\)/);
assert.match(entryStoryCss, /\.entry-llnk-live-post-flight\s*\{/);
assert.match(entryStoryCss, /\.entry-llnk-live-post-flight-beam\s*\{/);
assert.match(darkMode, /entry-chat-page-learn/);
assert.match(darkMode, /entry-chat-page-study/);
assert.match(darkMode, /entry-chat-page-challenge/);
assert.match(darkMode, /entry-chat-page-discovery/);
assert.match(darkModeCss, /entry-chat-page-download/);
assert.match(darkModeCss, /entry-chat-page-material/);
assert.match(darkModeCss, /e3mdq8z10/);
assert.match(darkModeCss, /e1ptpfbr1/);
assert.match(darkModeCss, /entry-chat-page-onboarding/);
assert.match(nativeLive, /entry-llnk-native-posts-will-add/);
assert.match(nativeLive, /detail: \{ count: added, ids: addedIds \}/);
assert.match(entry, /row\.style\.transform = `translate3d\(\$\{cardX\}px, \$\{cardY\}px, 0\) scale\(\$\{cardScale\}\)`/);
assert.match(entry, /const ownsRenderedBody = body\?\.dataset\?\.entryLlnkOwned === "1"/);
assert.match(entry, /function renderNativePostBody\(body, value\)/);
assert.match(entry, /entry-llnk-native-render-layer/);
assert.match(entryStoryCss, /\.entry-llnk-native-render-host > :not\(\.entry-llnk-native-render-layer\)/);
assert.match(nativeLive, /document\.visibilityState !== 'visible' \|\| syncBusy/);
assert.match(nativeLive, /finally \{\s*syncBusy = false;/);
assert.match(entry, /const postsByKey = new Map\(\)/);
assert.match(entry, /if \(matches\.length !== 1\) return/);
assert.doesNotMatch(entry, /posts\.slice\(0, rows\.length\)\.forEach\(\(post, index\)/);
assert.doesNotMatch(entry, /unboundNativeByIdentity/);
assert.doesNotMatch(entry, /liveByIdentity/);
assert.match(loader, /wrapHistoryMethod\("pushState"\)/);
assert.match(loader, /wrapHistoryMethod\("replaceState"\)/);
assert.match(loader, /const PROFILE_SCRIPT_FILES = \[\s*"src\/profile\.js"/);
assert.match(loader, /function isProfileRoute\(\)/);
assert.match(loader, /if \(isProfileRoute\(\)\) loadProfile\(\)/);
assert.doesNotMatch(loader, /routeCheckScheduled \|\| entryStoryLoaded/);
assert.match(loader, /routeCheckScheduled \|\| location\.href === lastRouteHref/);
assert.match(entry, /function isLiveEntryStoryPage\(\)/);
assert.match(entry, /location\.pathname !== "\/community\/entrystory\/list"/);
assert.match(entry, /params\.get\("sort"\) === "created"/);
assert.match(entry, /params\.get\("term"\) === "all"/);
assert.match(entry, /if \(!isLiveEntryStoryPage\(\) \|\| document\.visibilityState === "hidden"/);
assert.doesNotMatch(entry, /await refreshDraftOwner\(true\)/);
assert.match(entry, /url\.pathname === "\/redirect"/);
assert.match(entry, /submitArea\.insertBefore\(imageControl, submit\)/);
assert.match(entry, /button\.setAttribute\("aria-label", "이미지 첨부"\)/);
assert.doesNotMatch(entry, /setComposeButtonLabel\(button, "image", "이미지"\)/);
assert.match(entry, /button\.classList\.remove\("has-new-post"\)/);
assert.match(entry, /function isNewestEntryStoryPostVisible\(\)/);
assert.match(nativeLive, /const GOTO_BUTTON\s*= true/);
assert.match(nativeLive, /a\.href = `\/community\/entrystory\/\$\{postId\}`/);
assert.match(nativeLive, /a\.target = '_blank'/);
assert.match(entry, /if \(isNewestEntryStoryPostVisible\(\)\) button\.classList\.remove\("has-new-post"\)/);
assert.match(entry, /if \(!isEntryStoryPage\(\)\) \{\s*removeScrollTopButton\(\);/);
assert.match(entry, /if \(!isEntryStoryListPage\(\)\) \{\s*removeScrollTopButton\(\);\s*return;\s*\}\s*const button = \$\("\.entry-chat-entry-story-scroll-top/);
assert.doesNotMatch(entry, /setTimeout\(\(\) => up\?\.classList\.remove\("has-new-post"\)/);
assert.doesNotMatch(entry, /classList\.remove\("entry-chat-page-entrystory"/);
assert.match(common, /const API_BASE = "https:\/\/llnk\.kr\/api\/ringcl"/);
assert.match(entry, /const IMAGE_SHORT_LINK_BASE = "https:\/\/Llnk\.kr\/i"/);
assert.match(entry, /function getBlouplaImageUrl\(value\)/);
assert.match(entry, /const DRAFT_SUBMIT_SESSION_KEY = "entryLlnkEntryStoryDraftSubmitPending"/);
assert.match(entry, /rememberDraftSubmitPending\(submittedValue\);\s*discardStoredDraft\(\);/);
assert.match(entry, /function discardStoredDraft\(\)/);
assert.match(entry, /const failedValue = text\(state\.draftSubmittedValue \|\| readDraft\(\)\?\.value\)/);
assert.match(entry, /restoreDraftAfterFailure\(failedValue\)/);
  assert.match(entry, /function rememberDraftSubmitPending\(value\)/);
assert.match(entry, /function suppressPendingDraftInWriter\(writer = getWriter\(\)\)/);
  assert.match(entry, /function startPendingWriterSuppression\(writer = getWriter\(\)\)/);
  assert.match(entry, /startPendingWriterSuppression\(writer\)/);
  assert.match(entry, /state\.draftSubmitClearTimer = window\.setTimeout\(suppress, 250\)/);
  assert.match(entry, /window\.clearTimeout\(state\.draftSubmitClearTimer\)/);
  assert.match(entry, /restoreDraftSubmitPending\(\);\s*processRoot\(document\);\s*snapshotLiveRowPositions\(\);\s*startObserver\(\);/);
  assert.match(entry, /const roots = new Set\(\);\s*const arrivalRoots = new Set\(\);\s*let flushQueued = false;/);
  assert.match(entry, /window\.requestAnimationFrame\(flush\)/);
  assert.doesNotMatch(entry, /const schedule = debounce\(\(mutations\) =>/);
  assert.match(entry, /reconcileLiveRows\(getList\(\), state\.livePosts\)/);
assert.match(entry, /function isPendingSubmittedPost\(post, submittedValue = state\.draftSubmittedValue/);
assert.equal(entry.includes('.replace(/https:\\/\\/llnk\\.kr\\//gi, "https://llnk.kr/")'), true);
assert.match(entry, /discardStoredDraft\(\);\s*clearDraftRestoreEffects\(\);\s*removeImageAttachment\(null\);/);
assert.match(entry, /로봇이 아님\|로봇인지 확인\|사람인지 확인/);
assert.match(entry, /function startDraftFailureWatch\(\)/);
assert.match(entry, /characterData: true/);
assert.doesNotMatch(entry, /setTimeout\(\(\) => \{\s*removeImageAttachment\(null\);\s*renderWriterPreview\(\);\s*\}, 1200\)/);
  assert.match(entry, /!locallySubmittedIds\.has\(text\(post\.id\)\)/);
assert.doesNotMatch(entry, /document\.addEventListener\("DOMContentLoaded", init/);
assert.match(entry, /url\.hostname !== "img\.bloupla\.net"/);
assert.match(entry, /url\.searchParams\.set\("raw", "1"\)/);
assert.match(entry, /createImageCard\(\{ directUrl: blouplaImageUrl, fallbackUrl: url\.href, source: "bloupla" \}\)/);
assert.match(entry, /function showImageFallbackLink\(card\)/);
assert.match(entry, /card\.dataset\.entryLlnkFallbackUrl = marker\.fallbackUrl \|\| marker\.directUrl \|\| ""/);
assert.match(entry, /fallbackUrl\.hostname === "llnk\.kr"/);
assert.match(entry, /link\.href = llnkViewerUrl \|\| imageUrl/);
assert.match(entry, /if \(card && !showImageFallbackLink\(card\)\)/);
assert.match(entry, /image\.addEventListener\("error", \(\) => showImageFallbackLink\(card\), \{ once: true \}\)/);
assert.match(entryStoryCss, /\.entry-chat-image-fallback-link\s*\{[^}]*overflow-wrap:\s*anywhere/s);
assert.match(entry, /function createImageSourceBadge\(source\)/);
assert.match(entry, /function scanImageUploadError\(doc\)/);
assert.match(entry, /function showImageUploadError\(message\)/);
assert.match(entry, /entrybot-spaceship-1\.svg/);
assert.match(entry, /function formatImageUploadError\(\)\s*\{\s*return "업로드할 수 없는 파일입니다\."/);
assert.match(entry, /fail\("업로드할 수 없는 파일입니다\."\)/);
assert.match(entryStoryCss, /\.entry-chat-image-upload-error\s*\{/);
assert.match(entryStoryCss, /@keyframes entry-chat-image-error-flight/);
assert.match(darkModeCss, /a\[href\^="\/community\/tips\?tag="\]/);
assert.match(entry, /const label = isBloupla \? "Bloupla" : "Llnkkr"/);
assert.match(entry, /wrapper\.appendChild\(createImageSourceBadge\(card\.dataset\.entryLlnkSource\)\)/);
assert.match(entry, /function createBlouplaImageHost\(imageUrl\)/);
assert.match(entry, /function sizeImageCardForRatio\(card, ratio\)/);
assert.match(entryStoryCss, /\.entry-chat-bloupla-image-host\s*\{[^}]*max-height:\s*440px/s);
assert.match(entryStoryCss, /\.entry-chat-image-source-badge\.is-bloupla\s*\{[^}]*border:\s*2px solid #2563eb[^}]*border-color:\s*#2563eb[^}]*background:\s*#1c1d1f[^}]*color:\s*#f5f7fb/s);
assert.match(entryStoryCss, /\.entry-chat-image-source-badge\.is-llnk\s*\{[^}]*border:\s*2px solid #bfff00[^}]*border-color:\s*#bfff00[^}]*background:\s*#1c1d1f[^}]*color:\s*#f5f7fb/s);
assert.match(entryStoryCss, /html\.entry-chat-dark-mode\.entry-chat-page-entrystory body \.entry-chat-image-card \.entry-chat-image-spoiler > \.entry-chat-image-source-badge\.is-bloupla/);
assert.match(entryStoryCss, /html\.entry-chat-dark-mode\.entry-chat-page-entrystory body \.entry-chat-image-card \.entry-chat-image-spoiler > \.entry-chat-image-source-badge\.is-llnk/);
assert.match(entryStoryCss, /html\.entry-chat-dark-mode\.entry-chat-page-entrystory body \.entry-chat-image-card \.entry-chat-image-spoiler > \.entry-chat-image-source-badge\.is-llnk\s*\{[^}]*border:\s*2px solid #bfff00[^}]*border-color:\s*#bfff00[^}]*background-color:\s*#1c1d1f[^}]*color:\s*#f5f7fb/s);
assert.match(entry, /attachShadow\(\{ mode: "closed" \}\)/);
assert.match(entry, /chrome\.runtime\.getURL\("src\/bloupla-image-frame\.html"\)/);
assert.match(entry, /function playDraftRestoreAnimation\(writer, value\)/);
assert.match(entry, /assets\/draft-restore\/entrybot-spaceship-1\.svg/);
assert.doesNotMatch(entry, /entrybot-spaceship-\$\{frameNumber\}/);
assert.match(entry, /const characters = Array\.from\(draftValue\)/);
assert.match(entry, /typingProgress/);
assert.match(entry, /writer\.dataset\.entryLlnkDraftAnimating === "1"/);
assert.match(entry, /function measureDraftTextMetrics\(writer, value\)/);
assert.match(entry, /context\.measureText\(character\)\.width/);
assert.match(entry, /function draftFlightTiming\(characterCount, metrics = \{\}\)/);
assert.match(entry, /const travelWidth = Math\.max\(count \* 8, Number\(metrics\.totalWidth\) \|\| 0\)/);
assert.match(entry, /const sweepDistance = Math\.max\(72, Math\.min/);
assert.match(entry, /const typingDuration = Math\.max\(280, Math\.min\(2350, 220 \+ travelWidth \* 0\.22\)\)/);
assert.match(entry, /const sweepDuration = Math\.max\(520, Math\.min\(2700, typingDuration \+ 220\)\)/);
assert.match(entry, /sweepStartX \+ timing\.sweepDistance/);
assert.match(entry, /function draftFlightPose\(writer, progress, timing, writingProgress = 0\)/);
assert.match(entry, /x = mix\(sweepStartX, sweepEndX, writeT\)/);
assert.match(entry, /function draftBeamHeight\(writer, pose\)/);
assert.match(entry, /rect\.bottom - visualBeamTop/);
assert.match(entry, /beam\.style\.height = `\$\{draftBeamHeight\(writer, pose\)\}px`/);
assert.doesNotMatch(entry, /--entry-chat-draft-beam-height", "168px"/);
assert.match(entry, /exitStart: \(entryDuration \+ sweepDuration\) \/ duration/);
assert.match(entry, /const flightY = rect\.top - 82/);
assert.match(entry, /const entryEnd = timing\.entryEnd/);
assert.match(entry, /const exitStart = timing\.exitStart/);
assert.match(entry, /flight\.style\.transform = `translate3d/);
assert.doesNotMatch(entry, /flight\.animate\(/);
assert.doesNotMatch(entryStoryCss, /\.entry-chat-draft-flight-ship::before/);
assert.match(entry, /elapsed - timing\.typingStart/);
assert.doesNotMatch(entry, /holder\.appendChild\(particles\)/);
assert.doesNotMatch(entry, /panel\.className = "entry-chat-draft-restore-panel"/);
assert.match(entryStoryCss, /\.entry-chat-draft-flight-beam/);
assert.doesNotMatch(entryStoryCss, /@keyframes entry-chat-draft-flight\s*\{/);
assert.doesNotMatch(entryStoryCss, /\.entry-chat-draft-restore-(?:particles|message)/);
assert.match(darkMode, /entry-chat-dark-mode/);
for (const routeClass of [
  "entry-chat-page-entrystory",
  "entry-chat-page-project",
  "entry-chat-page-project-list",
  "entry-chat-page-project-edit",
  "entry-chat-page-profile",
  "entry-chat-page-ws",
  "entry-chat-page-home",
]) {
  assert.match(darkMode, new RegExp(routeClass));
}
assert.match(popup, /data-setting="darkMode"/);
assert.doesNotMatch(popup, /shortenPageButton/);
assert.doesNotMatch(popupJs, /chrome\.tabs/);
assert.doesNotMatch(popupJs, /SHORT_LINK_API/);
assert.match(darkModeCss, /css-8d1p21\.ezvkq1v0/);
assert.ok(manifest.content_scripts[0].css.includes("styles/dark-mode-pages.css"));
assert.match(darkModePagesCss, /e6ivz823/);
assert.match(darkModePagesCss, /e1jxxhw64/);
assert.match(darkModePagesCss, /e1eg1f7t0/);
assert.match(darkModePagesCss, /erwr35u8/);
assert.match(darkModePagesCss, /el6de3b1/);
assert.match(darkModePagesCss, /e1qduyw34/);
assert.match(darkMode, /applyPageSurfaceFixes/);
assert.match(darkModeCss, /\[class\*="ea7lx0i"\]/);
assert.match(darkModeCss, /e1xq8jz71/);
assert.match(entryStoryCss, /\.entry-chat-md-spoiler:not\(\.is-revealed\) \*/);
assert.match(entryStoryCss, /-webkit-text-fill-color: transparent !important/);
assert.match(entryStoryCss, /background-color: transparent !important/);
assert.match(entry, /function animateMetricDial\(element, previous, next\)/);
assert.match(entry, /function metricNumberBox\(element, previous, next\)/);
assert.match(entry, /entry-llnk-metric-dial-layer/);
assert.match(entryStoryCss, /\.entry-llnk-metric-dial-layer/);
assert.match(entryStoryCss, /font-variant-numeric:\s*tabular-nums/);
assert.doesNotMatch(entryStoryCss, /entry-llnk-metric-dial\s*\{[^}]*color:\s*transparent/s);
assert.doesNotMatch(
  [entry, common, loader, nativeLive, popupJs, darkMode].join("\n"),
  /\bconsole\.(?:log|info|debug|warn|error|trace|group|groupEnd|table)\b/
);
assert.match(darkModeCss, /textarea#Write\s*\{\s*background-color:\s*var\(--entry-chat-dark-bg\)\s*!important/);
assert.match(darkModeCss, /e1b6l2yr2[^}]*\{\s*background-color:\s*transparent\s*!important/);
assert.match(darkModeCss, /e1lgujxn0[^}]*\{[^}]*background-color:\s*#242529\s*!important/s);
assert.match(darkModeCss, /e1lgujxn2[^}]*\{[^}]*background-color:\s*#242529\s*!important/s);
assert.match(darkModeCss, /e1lgujxn3[^}]*\{[^}]*background-color:\s*#242529\s*!important/s);
assert.match(darkModeCss, /e1lgujxn5[^}]*\{[^}]*background-color:\s*#242529\s*!important/s);
assert.match(darkModeCss, /e1lgujxn8[^}]*\{[^}]*background-color:\s*transparent\s*!important/s);
assert.match(darkModeCss, /e1lgujxn8[^}]*elhpwdj1[^}]*background-color:\s*#242529\s*!important/s);
assert.match(darkModeCss, /e1lgujxn8[^}]*elhpwdj1[^}]*::before[^}]*background-color:\s*transparent\s*!important/s);
assert.match(entryStoryCss, /entry-chat-story-toolbar-toggle[^}]*width:\s*auto[^}]*min-width:\s*0[^}]*height:\s*38px[^}]*border-radius:\s*19px/s);
assert.match(entryStoryCss, /entry-chat-story-toolbar-toggle[^}]*font-family:\s*inherit[^}]*line-height:\s*normal[^}]*letter-spacing:\s*0/s);
assert.match(entryStoryCss, /e1lgujxn8[^}]*\{[^}]*display:\s*flex[^}]*left:\s*0\s*!important[^}]*right:\s*-16px\s*!important/s);
assert.match(entryStoryCss, /entry-chat-story-settings-toggle\s*\{[^}]*margin-right:\s*auto/s);
assert.match(entryStoryCss, /entry-chat-story-toolbar-caret[^}]*width:\s*8px[^}]*height:\s*6px[^}]*IcoSelectArrow\.svg[^}]*transition:\s*transform 160ms ease/s);
assert.match(entryStoryCss, /aria-expanded="true"[^}]*entry-chat-story-toolbar-caret[^}]*rotate\(180deg\)/s);
assert.match(entryStoryCss, /entry-chat-story-toolbar-toggle:hover[^}]*entry-chat-story-toolbar-caret[^}]*aria-expanded="true"[^}]*rotate\(180deg\)/s);
assert.match(entryStoryCss, /e1lgujxn8[^}]*elhpwdj1[^}]*span::after[^}]*transform:\s*none\s*!important[^}]*transition:\s*transform 160ms ease/s);
assert.match(entryStoryCss, /e1lgujxn8[^}]*elhpwdj1[^}]*:hover[^}]*span::after[^}]*rotate\(180deg\)\s*!important/s);
assert.match(entryStoryCss, /entry-llnk-native-sort-open[^}]*elhpwdj1[^}]*span::after[^}]*rotate\(180deg\)\s*!important/s);
assert.match(entry, /function syncNativeStorySortOpenState\(\)[\s\S]*getComputedStyle\(panel\)[\s\S]*entry-llnk-native-sort-open/);
assert.match(entry, /function bindReplyFoldScrollStabilizer\(\)[\s\S]*anchorTop[\s\S]*window\.scrollBy\(0, delta\)/);
assert.match(darkModeCss, /eqmdslz0[^}]*:has\(> \[class~="e1qasnlc1"\]\)[^}]*background-color:\s*transparent\s*!important/s);
assert.match(darkModeCss, /e1qasnlc1[^}]*e1qasnlc2[^}]*e1qasnlc0[^}]*e1qasnlc3[^}]*background-color:\s*var\(--entry-chat-dark-bg\)\s*!important/s);
assert.match(darkModeCss, /e39c0e70[^}]*background-color:\s*var\(--entry-chat-dark-bg,\s*#1c1d1f\)\s*!important/s);
assert.match(darkModeCss, /css-1drqr8w\.etjmww10[^}]*background-color:\s*#242529\s*!important/s);
assert.match(darkModeCss, /eeidpoo5[^}]*e6rlvg80[^}]*:first-child\s*\{[^}]*background-color:\s*#fff\s*!important[^}]*color:\s*#20242c\s*!important/s);
assert.match(darkModeCss, /entry-chat-dark-mode[^}]*eeidpoo5[^}]*e6rlvg80[^}]*:first-child\s*\{[^}]*background-color:\s*#242529\s*!important[^}]*color:\s*#f5f7fb\s*!important/s);
assert.match(darkModeCss, /entry-chat-dark-mode[^}]*eeidpoo5[^}]*e6rlvg80[^}]*:first-child:hover\s*\{[^}]*background-color:\s*#2b2d31\s*!important/s);
assert.match(darkModeCss, /eoyck2u0[^}]*:has\(> \[class~="eeidpoo1"\] > \[class~="eeidpoo5"\]\)[^}]*overflow:\s*hidden\s*!important/s);
assert.match(darkModeCss, /e1yojj2m1[^}]*e1yojj2m3[^}]*e39c0e78[^}]*background-color:\s*#242529\s*!important/s);
assert.match(darkModeCss, /e39c0e78[^}]*textarea[^}]*background-color:\s*transparent\s*!important/s);
assert.match(darkModeCss, /button\.etjmww10:disabled[^}]*background-color:\s*#242529\s*!important/s);
assert.match(entryStoryCss, /css-4e8bhg\.e1qasnlc1[\s\S]*e1qasnlc3[\s\S]*background-color:\s*transparent\s*!important/);
assert.match(entryStoryCss, /e1qasnlc1[^}]*ed0ret0[^}]*background-color:\s*#242529\s*!important/s);
assert.match(entryStoryCss, /ed0ret0[^}]*ed0ret11[^}]*ed0ret3[^}]*textarea[^}]*background-color:\s*transparent\s*!important/s);
assert.match(entryStoryCss, /css-4e8bhg\.e1qasnlc1[^}]*css-1cyfuwa\.ed0ret0 textarea#Write[^}]*background-color:\s*#242529\s*!important/s);
assert.match(entry, /const STORY_FILTER_OPTIONS = Object\.freeze\(\[/);
assert.match(entry, /projectLinks[^\n]*엔트리 작품 링크/);
assert.match(entry, /entryLinks[^\n]*엔트리 링크/);
assert.match(entry, /externalLinks[^\n]*엔트리 외부 링크/);
assert.match(entry, /allLinks[^\n]*모든 링크/);
assert.match(entry, /images[^\n]*이미지/);
assert.match(entry, /entryEmoticons[^\n]*엔트리 이모티콘/);
assert.match(entry, /allLinks[^\n]*children: \["entryLinks", "externalLinks"\]/);
assert.match(entry, /entryLinks[^\n]*children: \["projectLinks"\]/);
assert.match(entry, /function setStoryFilterEnabled\(key, enabled\)/);
assert.match(entry, /function storyFilterUrlFromAnchor\(link\)/);
assert.match(entry, /url\.pathname === "\/redirect"/);
assert.match(entry, /link\.matches\("\.entry-chat-image-link"\)/);
assert.match(entry, /hasEntryEmoticon/);
assert.match(entry, /function createStoryFilterPanel\(\)/);
assert.match(entry, /function createStorySettingsPanel\(\)/);
assert.match(entry, /function createStoryToolbarButton\(className, dataKey, label, iconName\)/);
assert.match(entry, /function syncLiveStoryToolbarScope\(\)[\s\S]*entry-llnk-live-story-toolbar[\s\S]*isLiveEntryStoryPage\(\)/);
assert.match(entry, /function ensureStoryFilterMenu\(\)\s*\{\s*syncLiveStoryToolbarScope\(\);\s*if \(!isLiveEntryStoryPage\(\)\) \{\s*\$\("\[data-entry-llnk-link-filter='1'\]"\)\?\.remove\(\);\s*\$\("\[data-entry-llnk-story-filter-panel='1'\]"\)\?\.remove\(\);\s*\$\("\[data-entry-llnk-story-settings='1'\]"\)\?\.remove\(\);\s*\$\("\[data-entry-llnk-story-settings-panel='1'\]"\)\?\.remove\(\);/s);
assert.match(entryStoryCss, /html\.entry-chat-page-entrystory\.entry-llnk-live-story-toolbar body \[class~="e1lgujxn8"\]/);
assert.match(entry, /entryLlnkLinkFilter", "필터", "filter_alt"/);
assert.match(entry, /entryLlnkStorySettings", "설정", "settings"/);
assert.match(entry, /const STORY_SETTING_OPTIONS = Object\.freeze\(\[/);
assert.match(entry, /darkMode.*다크모드.*dark_mode/);
assert.match(entry, /spaceshipMotion.*우주선 모션.*rocket_launch/);
assert.match(entry, /imageSpoiler.*이미지 스포일러.*hide_image/);
assert.match(entry, /shortenProjectLinks.*작품 링크 줄이기.*link/);
assert.match(entry, /shortenProjectLinksEnabled: true/);
assert.match(entry, /entryLlnkProjectOriginalText/);
assert.match(entry, /if \(!state\.shortenProjectLinksEnabled\)/);
assert.match(entry, /original && original !== "\[작품 링크\]"/);
assert.match(entry, /if \(key === "shortenProjectLinks"\)/);
assert.match(entry, /label !== "\[작품 링크\]"/);
assert.match(entry, /const wasShortened =/);
assert.match(entry, /state\.shortenProjectLinksEnabled = enabled;\s*shortenProjectLinks\(document\)/);
assert.match(entry, /async function saveStorySetting\(key, enabled\)/);
assert.match(entry, /row\.setAttribute\("role", "switch"\)/);
assert.match(entry, /storyFilters: \{ \.\.\.state\.storyFilters \}/);
assert.doesNotMatch(entry, /선택한 항목이 있는 글을 숨깁니다|작품 링크가 포함된 글|첨부 이미지가 포함된 글/);
assert.match(entryStoryCss, /entry-chat-story-link-filter-toggle\.is-active[^}]*border-color:\s*transparent[^}]*background:\s*transparent/s);
assert.match(entryStoryCss, /entry-chat-story-link-filter-toggle\.is-active \.entry-chat-story-toolbar-icon[^}]*color:\s*#16d8a3\s*!important/s);
assert.match(entryStoryCss, /\.entry-chat-story-filter-switch i\s*\{[^}]*transition:\s*transform 190ms/s);
assert.match(entryStoryCss, /\.entry-chat-story-filter-option\.is-active \.entry-chat-story-filter-switch i\s*\{[^}]*translateX\(16px\)/s);
assert.match(darkModeCss, /entry-chat-story-filter-panel[^}]*background:\s*#222327\s*!important/s);
assert.match(darkModeCss, /entry-chat-story-toolbar-toggle[^}]*background:\s*transparent\s*!important/s);
assert.match(darkModeCss, /entry-chat-story-filter-option\.is-active \.entry-chat-story-filter-switch[^}]*background:\s*#16d8a3\s*!important/s);
assert.match(darkModeCss, /e1lgujxn8[^}]*entry-chat-story-toolbar-toggle[^}]*width:\s*auto[^}]*min-width:\s*0[^}]*max-width:\s*none/s);
assert.match(darkModeCss, /entry-chat-story-link-filter-toggle\.is-active[^}]*border-color:\s*transparent\s*!important/s);
assert.match(darkModeCss, /entry-chat-story-link-filter-toggle\.is-active \.entry-chat-story-toolbar-icon[^}]*color:\s*#16d8a3\s*!important/s);
assert.match(darkModeCss, /entry-chat-dark-mode\.entry-chat-page-entrystory body \.entry-chat-story-link-filter-toggle\.is-active \.entry-chat-story-toolbar-icon[^}]*color:\s*#16d8a3\s*!important/s);
assert.match(darkModeCss, /entry-chat-story-filter-option:hover[^}]*background:\s*#303238\s*!important/s);
assert.match(darkModeCss, /entry-chat-dark-mode \.entry-chat-story-filter-option\s*\{[^}]*background:\s*transparent\s*!important/s);
assert.match(darkModeCss, /entry-chat-story-filter-panel \.entry-chat-story-filter-option\s*\{[^}]*background:\s*transparent\s*!important/s);
assert.match(darkModeCss, /entry-chat-story-filter-panel \.entry-chat-story-filter-option:hover\s*\{[^}]*background:\s*#303238\s*!important/s);
assert.match(darkModeCss, /entry-chat-story-toolbar-toggle:hover[^}]*background:\s*transparent\s*!important/s);
assert.match(darkModeCss, /e1lgujxn8[^}]*elhpwdj1[^}]*:hover[^}]*background:\s*#242529\s*!important/s);
assert.match(entryStoryCss, /entry-chat-story-toolbar-icon[^}]*background:\s*transparent\s*!important[^}]*color:\s*inherit\s*!important/s);
assert.match(entryStoryCss, /entry-chat-story-toolbar-toggle[^}]*gap:\s*0[^}]*width:\s*auto[^}]*padding:\s*0 18px/s);
assert.match(entryStoryCss, /entry-chat-story-toolbar-icon[^}]*width:\s*20px[^}]*margin:\s*0 8px 0 0[^}]*font-size:\s*20px\s*!important/s);
assert.match(entryStoryCss, /entry-chat-story-toolbar-caret[^}]*margin:\s*0 0 0 18px/s);
assert.match(entryStoryCss, /entry-chat-story-toolbar-label[^}]*background:\s*transparent\s*!important[^}]*color:\s*inherit\s*!important/s);
assert.match(entryStoryCss, /entry-chat-story-setting-icon[^}]*background:\s*transparent\s*!important[^}]*-webkit-text-fill-color:\s*currentColor\s*!important/s);
assert.match(entryStoryCss, /entry-chat-story-filter-heading strong[^}]*color:\s*inherit\s*!important/s);
assert.match(entryStoryCss, /entry-chat-story-filter-heading[^}]*background:\s*transparent\s*!important[^}]*background-color:\s*transparent\s*!important/s);
assert.doesNotMatch(darkModeCss, /entry-chat-dark-mode \.entry-chat-story-filter-panel,\s*html\.entry-chat-themed \.entry-chat-story-filter-panel/);
assert.match(entryStoryCss, /entry-chat-story-filter-panel[^}]*width:\s*min\(230px[^}]*padding:\s*8px/s);
assert.match(entryStoryCss, /entry-chat-story-filter-panel,\s*\.entry-chat-story-filter-panel \*[^}]*text-shadow:\s*none\s*!important[^}]*-webkit-text-stroke:\s*0 transparent\s*!important/s);
assert.match(entryStoryCss, /entry-chat-story-filter-copy strong[^}]*background:\s*transparent\s*!important[^}]*background-color:\s*transparent\s*!important/s);
assert.match(entryStoryCss, /entry-chat-story-filter-option[^}]*gap:\s*8px[^}]*min-height:\s*40px[^}]*padding:\s*4px 6px/s);
assert.match(entryStoryCss, /entry-chat-story-filter-option\.is-depth-1\s*\{[^}]*padding-left:\s*20px/s);
assert.match(entryStoryCss, /entry-chat-story-filter-option\.is-depth-2\s*\{[^}]*padding-left:\s*34px/s);
assert.match(entryStoryCss, /entry-chat-story-filter-copy strong[^}]*font-size:\s*14px[^}]*font-weight:\s*600/s);
assert.match(entryStoryCss, /entry-chat-story-filter-switch[^}]*width:\s*38px[^}]*height:\s*22px/s);
assert.match(darkModeCss, /entry-chat-dark-mode\.entry-chat-page-entrystory body \.entry-chat-story-filter-panel\s*\{[^}]*background:\s*#222327\s*!important/s);
assert.match(darkModeCss, /entry-chat-dark-mode\.entry-chat-page-entrystory body \.entry-chat-story-filter-panel \.entry-chat-story-filter-heading\s*\{[^}]*background:\s*transparent\s*!important/s);
assert.match(darkModeCss, /entry-chat-story-filter-panel :is\([^)]*entry-chat-story-filter-copy strong[^)]*\)\s*\{[^}]*background:\s*transparent\s*!important[^}]*text-shadow:\s*none\s*!important/s);
assert.doesNotMatch(popup, /data-setting="hidePromotions"|작품 링크 필터/);
assert.doesNotMatch(popupJs, /hidePromotions/);
assert.match(entryStoryCss, /e1lgujxn5[^}]*eqmdslz0[^}]*\{[^}]*border:\s*1px solid transparent\s*!important/s);
assert.match(entryStoryCss, /e19ceda91[^}]*ul li > a\s*\{[^}]*cursor:\s*pointer\s*!important/s);
assert.match(darkModeCss, /eqmdslz0[^}]*\{[^}]*border:\s*1px solid transparent\s*!important/s);
assert.match(darkModeCss, /eqmdslz0[^}]*e1uj27uy0[^}]*\{[^}]*border-radius:\s*11px\s*!important/s);
assert.doesNotMatch(darkModeCss, /:where\(\[class\*="eqmdslz"\],\s*\[class\*="eewwvxq"\]\)\s*\{[^}]*border:/s);
assert.match(darkModeCss, /e1lwjzl20[^}]*\{[^}]*transition:\s*background-color 180ms ease/s);
assert.match(darkModeCss, /e1lwjzl20[^}]*:hover[^}]*\{[^}]*background-color:\s*#12c99a\s*!important/s);
assert.match(darkModeCss, /entry-chat-page-profile body \.css-m0nf83\.ebifrqs1[^}]*background:\s*transparent\s*!important/s);
assert.match(darkModeCss, /button\.active\.css-1oz7jgs\.e1raq2kp3[^}]*background-color:\s*transparent\s*!important/s);
assert.match(profileCss, /css-m0nf83[^}]*css-1oz7jgs[^}]*background-color:\s*transparent\s*!important/s);
assert.match(profile, /normalizeProfileCommunityBackgrounds/);
assert.match(profile, /style\.setProperty\("background-color",\s*"transparent",\s*"important"\)/);
assert.doesNotMatch(entryStoryCss, /entry-llnk-metric-dial::before\s*\{[^}]*content:/s);
assert.match(darkModeCss, /\.entry-chat-md-spoiler:not\(\.is-revealed\) \*/);
assert.doesNotMatch(popup, /엔트리이야기 열기|초대 코드|사용 권한/);

console.log("링클 기능 정책 검사 통과");
